# PodDisruptionBudgets - ensure availability during node drains/upgrades
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: webapps
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: checkoutservice-pdb
  namespace: webapps
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: checkoutservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cartservice-pdb
  namespace: webapps
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: cartservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: paymentservice-pdb
  namespace: webapps
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: paymentservice
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: productcatalogservice-pdb
  namespace: webapps
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: productcatalogservice
