apiVersion: v1
kind: ServiceAccount
metadata:
  name: boutique-sa
  namespace: webapps
  annotations:
    # Replace with your AWS account ID and OIDC provider URL after terraform apply
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/online-boutique-prod-sa-role
automountServiceAccountToken: false
